"""Mint / refresh the SolMan session cookie via SAML/IAS SSO.

The target system may authenticate through SAP Cloud Identity Services (IAS)
rather than Windows SPNego, so ADT-based SSO cookie tools cannot be reused
(they force the ``/sap/bc/adt/`` path, which is usually closed on a Focused
Build box). This opens a real Edge window against an *allowed* OData path, lets
SAML->IAS complete (interactive on first run, silent afterwards thanks to the
persistent profile), reads the resulting session cookies via CDP (incl.
HttpOnly), and writes them to ``%USERPROFILE%\\.solman-mcp\\cookies.txt`` in
Netscape format.

Run this out-of-band whenever the MCP server reports the session expired. The
server itself is cookie-only and never opens a browser.

Usage:
    python refresh_session.py            # default 5 min window for interactive login
    python refresh_session.py --timeout 120
    python refresh_session.py --headless # only works once the IAS session is warm
"""
from __future__ import annotations

import argparse
import sys
import time
from urllib.parse import urlparse

from playwright.sync_api import sync_playwright

import config


def _probe_url() -> str:
    # An allowed, cheap, authenticated GET. If this returns edmx XML we know the
    # SAML assertion has been consumed and the SAP session cookie exists.
    return f"{config.BASE_URL}{config.SVC_GENERIC}/$metadata?sap-client={config.SAP_CLIENT}"


def _session_cookie_present(cookies: list[dict]) -> bool:
    host = config.SAP_HOST
    for c in cookies:
        if c.get("name", "").startswith(config.SESSION_COOKIE_PREFIX) and host in c.get("domain", ""):
            return True
    return False


def _write_netscape(cookies: list[dict], path) -> int:
    """Write host-scoped cookies in Netscape format (curl-compatible)."""
    host = config.SAP_HOST
    lines = ["# Netscape HTTP Cookie File", "# Generated by refresh_session.py", ""]
    written = 0
    for c in cookies:
        domain = c.get("domain", "")
        if host not in domain:
            continue
        # host-only cookie -> leading-dot FALSE
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires") or 0)
        if expires < 0:
            expires = 0
        lines.append(
            "\t".join([
                domain, include_sub, c.get("path", "/"), secure,
                str(expires), c.get("name", ""), c.get("value", ""),
            ])
        )
        written += 1
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return written


def refresh(timeout_s: int, headless: bool) -> int:
    config.EDGE_PROFILE.mkdir(parents=True, exist_ok=True)
    probe = _probe_url()
    print(f"[refresh] target : {config.BASE_URL} (client {config.SAP_CLIENT})")
    print(f"[refresh] profile: {config.EDGE_PROFILE}")
    print(f"[refresh] cookie : {config.COOKIE_FILE}")

    with sync_playwright() as pw:
        ctx = pw.chromium.launch_persistent_context(
            user_data_dir=str(config.EDGE_PROFILE),
            channel="msedge",
            headless=headless,
            ignore_https_errors=True,
            args=["--start-maximized"],
        )
        try:
            page = ctx.pages[0] if ctx.pages else ctx.new_page()
            print("[refresh] navigating; complete the IAS login if prompted...")
            try:
                page.goto(probe, wait_until="domcontentloaded", timeout=60_000)
            except Exception as exc:  # noqa: BLE001 - navigation may bounce through IdP
                print(f"[refresh] initial nav note: {exc}")

            # Poll the real API until it returns metadata (edmx) — i.e. SAML/IAS login
            # is actually complete. Cookie *presence* isn't enough: a pre-auth
            # SAP_SESSIONID appears before login finishes.
            deadline = time.monotonic() + timeout_s
            ok = False
            while time.monotonic() < deadline:
                try:
                    resp = ctx.request.get(probe, ignore_https_errors=True)
                    if resp.ok and "edmx" in resp.text().lower():
                        ok = True
                        break
                except Exception:  # noqa: BLE001 - transient during redirects
                    pass
                time.sleep(3)
            if not ok:
                print("[refresh] FAILED: not authenticated within timeout — "
                      "complete the IAS login in the browser window.", file=sys.stderr)
                return 2
            n = _write_netscape(ctx.cookies(), config.COOKIE_FILE)
            print(f"[refresh] OK: session verified; wrote {n} cookies.")
            return 0
        finally:
            ctx.close()


def main() -> None:
    ap = argparse.ArgumentParser(description="Refresh the SolMan SSO cookie.")
    ap.add_argument("--timeout", type=int, default=300, help="seconds to wait for login (default 300)")
    ap.add_argument("--headless", action="store_true", help="run headless (only if IAS session is warm)")
    args = ap.parse_args()
    sys.exit(refresh(args.timeout, args.headless))


if __name__ == "__main__":
    main()
